
version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - '5000:5000'
    networks:
      app_network:
        ipv4_address: 192.168.1.2

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    networks:
      app_network:
        ipv4_address: 192.168.1.3

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

